name: Veian's BLOG
markdown: redcarpet
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
title : Veian's blog
tagline: veian blog
author :
  name : veian
  email : q.787583174@gmail.com
  github : veian

production_url : http://e2024.com

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.13

  BASE_PATH : false

  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

  comments :
    provider : disqus
    disqus :
      short_name : imaxbin
   
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-123-12'
